name: wallyapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  # firebase_auth: ^0.15.0
  # firebase_storage: ^3.1.1
  firebase_ml_vision: ^0.9.10
  # firebase_messaging: ^6.0.9
  # google_sign_in: ^4.1.1
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^2.0.0
  image_picker: ^0.6.2+3
  flutter_spinkit: ^4.1.1+1
  # flutter_custom_tabs: ^0.6.0
  # firebase_dynamic_links: ^0.5.0+9
  share: ^0.6.3+5
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  # firebase_ml_vision: ^0.12.0+3
  firebase_messaging: ^6.0.16
  google_sign_in: ^4.5.9
  flutter_custom_tabs: ^0.7.0
  firebase_dynamic_links: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/logo_background.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: productsans
      fonts:
        - asset: assets/ProductSans-Regular.ttf